### PR TITLE
Fixes #134 - Make path to chrome extension os-independent

### LINKED ISSUE #134: npm run chrome does not work on windows
Trying to run the extension on chrome on windows almost works but then spouts the error : 

Failed to load extension from: C:\Program Files(x86)\Google\Chrome\Application\69.0.3497.100\dist\chrome. Manifest file is missing or unreadable.  

Clicking ok opens the chrome browser to the webcompat website. 

(As screenshot shows, firefox works but opera does not)

operanorchrome

### PR DESCRIPTION
**Pull request by laghee**
This should allow for better cross-platform functionality.

### CODE REVIEW

File: chrome/run.js [hunk 1]
```diff
@@ -6,7 +6,8 @@
 
 const chromeLaunch = require("chrome-launch");
 const url = "https://webcompat.com/";
-const args = ["--load-extension=./dist/chrome"];
+const extPath = `${__dirname}/../dist/chrome`;
```
Comment (miketaylr) [inline chrome/run.js]: Neat, TIL https://nodejs.org/api/modules.html#modules_dirname is a thing.

**Comment by miketaylr** [comment]
Thanks, @laghee. 🌟
